### ISSUE TITLE
[bug] Can't build due to an SSL issue

### ISSUE THREAD

**Issue by alexander-lee** [majewsky/rust-jmdict#1]
Tried to run the curl command in the script:
`curl https://dl.xyrillian.de/jmdict/entrypack-v1-2021-07-19.json.gz` seems to state that the SSL certificate on your domain has expired :(

**Comment by majewsky** [comment]
My certificate looks fine. I'm guessing that your CA bundle is outdated, see https://scotthelme.co.uk/lets-encrypt-old-root-expiration/
